### ISSUE TITLE
Sync with upstream from 3.14.1 to 4.4.1

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/matomo#6]
We also need to write the upgrade process in the "Releases" page of Notion

https://github.com/matomo-org/matomo/releases/tag/4.4.1

**Comment by EtienneM** [comment]
Interested customers: 
https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700080784

**Comment by yohann-bacha** [comment]
It seems we don't want to support Matomo anymore, as it is not one of our supported buildpacks. See more here : https://scalingo.slack.com/archives/C04DTBENZAL/p1681736687929779?thread_ts=1681734852.109739&cid=C04DTBENZAL
